/***********************************************************************************
 * Description      : DTO_ServiceResponse
 * @author          : Malinda (SLK)
 * @since           : 27-04-2016
 * Copyright 2016 ABSI. All rights reserved.  
 ***********************************************************************************/
global class DTO_ServiceResponse{
    webservice Boolean isSuccess;
    webservice String errorCode;
    webservice String errorMessage; 
}
